### ISSUE TITLE
Good to see smeone taking on the KAP140

### ISSUE THREAD

**Issue by N6722C** [FS2020-USER-TESTER/KAP140-MOD-PACKAGE#2]
Good to see someone else taking on the KAP140.

What I had hoped to see by now,  is the  ALT ARM  button integrated into the operation of the AP.
Asobo completely left it out  of doing anything but animating.

Maybe, this is something that can be considered to improve this MSFS AP  ?

**Comment by jbobzin-insyde** [comment]
The 'Real Life' software for the KAP140 has mostly eliminated a use for the ARM button.  
1. With AP on, when target altitude is set with the knobs, the pilot guide says arming is automatic and no need to press ARM button.
2. Presumably hitting the button when arming is auto-on would turn it off and the airplane would fly past the target. But this is not a feature available in the Asobo core AP.
3. With AP off, there is an alert function which again does not need the ARM button to function. Not all airplanes map the altitude alert sound. 
Thanks for the feedback.  I am open to suggestions on ARM button or otherwise.
